# Header
menu: #导航栏连接
  Principal: /
  PDF: /pdf
  Marcadores: /marcadores
  # Category: /category
  Arquivos: /arquivos #/archives #归档页面URL 自定义页面标题: /自定义页面URL
  Sobre: /sobre
  Github: https://github.com/fhcflx/cpc-neuro





rss: /atom.xml #rss地址  默认即可

#feed:
#  type: atom       #feed 类型 (atom/rss2)
#  path: /atom.xml   #rss 路径
#  limit: 20        #在 rss 中最多生成的文章数(0显示所有)


#icon http://fontawesome.io/
#首页显示
article_index:
  -  title: Protocolos de Tratamento
     content: Manual de protocolos de quimioterapia usados no tratamento de pacientes com tumores cerebrais.
     icon: icon-book
  -  title: Equipe do GPMCP
     content: Juvenia B Fontenele，Francisco H C Felix
     icon: icon-bolt
  -  title: Banco de dados
     content: Relatórios dinâmicos do banco de dados de pacientes com tumores cerebrais.
     icon: icon-lab
  -  title: Github #Github
     content: fhcflx/cpc-neuro
     icon: icon-github-alt



# Content
excerpt_link: Leia mais  #阅读更多的文字显示
# fancybox: false  #开启fancybox效果




# Miscellaneous #社交网络和统计连接地址
baidu_analytics: //hm.baidu.com/hm.js? #百度统计
favicon: /css/favicon.ico
logo: /css/logo.png
